# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "183fb278077458dc02b21634e784cff4"
application_url = "https://trademarks-janet-manner-literacy.trycloudflare.com"
embedded = true
name = "Flotara"
handle = "flotara"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://trademarks-janet-manner-literacy.trycloudflare.com/auth/callback",
  "https://trademarks-janet-manner-literacy.trycloudflare.com/auth/shopify/callback",
  "https://trademarks-janet-manner-literacy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
